<?php

namespace TeamBuilder\CovoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdherentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherentRepository extends EntityRepository
{
    public function findAllAdherentById(int $idp)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'select a from TeamBuilderCovoiturageBundle:Adherent a where a.id='.$idp
                        )
                ->getResult();
    }
}
