<?php

namespace TeamBuilder\CovoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PointarretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointarretRepository extends EntityRepository
{
}
