<?php

namespace Proxies\__CG__\TeamBuilder\CovoiturageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trajet extends \TeamBuilder\CovoiturageBundle\Entity\Trajet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idTrajet', 'jours', 'heure', 'frequence', 'typeTrajet', 'places', 'bagages', 'commentaire', 'kilometrage', 'prix', 'villeArrivee', 'villeDepart', 'codeHtml', 'idConducteur', 'idVoiture');
        }

        return array('__isInitialized__', 'idTrajet', 'jours', 'heure', 'frequence', 'typeTrajet', 'places', 'bagages', 'commentaire', 'kilometrage', 'prix', 'villeArrivee', 'villeDepart', 'codeHtml', 'idConducteur', 'idVoiture');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Trajet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdTrajet()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTrajet();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTrajet', array());

        return parent::getIdTrajet();
    }

    /**
     * {@inheritDoc}
     */
    public function setJours($jours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJours', array($jours));

        return parent::setJours($jours);
    }

    /**
     * {@inheritDoc}
     */
    public function getJours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJours', array());

        return parent::getJours();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure($heure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', array($heure));

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', array());

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrequence($frequence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrequence', array($frequence));

        return parent::setFrequence($frequence);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrequence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrequence', array());

        return parent::getFrequence();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeTrajet($typeTrajet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeTrajet', array($typeTrajet));

        return parent::setTypeTrajet($typeTrajet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeTrajet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeTrajet', array());

        return parent::getTypeTrajet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaces($places)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaces', array($places));

        return parent::setPlaces($places);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaces', array());

        return parent::getPlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setBagages($bagages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBagages', array($bagages));

        return parent::setBagages($bagages);
    }

    /**
     * {@inheritDoc}
     */
    public function getBagages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBagages', array());

        return parent::getBagages();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', array($commentaire));

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', array());

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setKilometrage($kilometrage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKilometrage', array($kilometrage));

        return parent::setKilometrage($kilometrage);
    }

    /**
     * {@inheritDoc}
     */
    public function getKilometrage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKilometrage', array());

        return parent::getKilometrage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleArrivee($villeArrivee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleArrivee', array($villeArrivee));

        return parent::setVilleArrivee($villeArrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleArrivee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleArrivee', array());

        return parent::getVilleArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleDepart($villeDepart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleDepart', array($villeDepart));

        return parent::setVilleDepart($villeDepart);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleDepart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleDepart', array());

        return parent::getVilleDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeHtml($codeHtml)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeHtml', array($codeHtml));

        return parent::setCodeHtml($codeHtml);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeHtml()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeHtml', array());

        return parent::getCodeHtml();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdConducteur(\Covoiturage\UserBundle\Entity\User $idConducteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdConducteur', array($idConducteur));

        return parent::setIdConducteur($idConducteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdConducteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdConducteur', array());

        return parent::getIdConducteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVoiture(\TeamBuilder\CovoiturageBundle\Entity\Voiture $idVoiture = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVoiture', array($idVoiture));

        return parent::setIdVoiture($idVoiture);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVoiture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVoiture', array());

        return parent::getIdVoiture();
    }

}
